config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'blog_posts#index'
  # Blog_Post routes
  resources :blog_posts
  # get '/blog_posts/new', to: 'blog_posts#new', as: :new_blog_post
  # get '/blog_posts/:id', to: 'blog_posts#show', as: :blog_post
  # patch '/blog_posts/:id', to: 'blog_posts#update', as: :update_blog_post
  # delete '/blog_posts/:id', to: 'blog_posts#destroy', as: :delete_blog_post
  # get '/blog_posts/:id/edit', to: 'blog_posts#edit', as: :edit_blog_post
  # post '/blog_posts', to: 'blog_posts#create', as: :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# frozen_string_literal: true

# blog_posts table Model
class BlogPost < ApplicationRecord
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true
  scope :sorted, -> { order(published_at: :desc, updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :scheduled, -> { where('published_at > ?', Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# Class that handle the global controller configuration
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_to_root

  def redirect_to_root
    redirect_to root_path
  end

  include Pagy::Backend
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

# Controller that handles /BlogPost/ routes.
class BlogPostsController < ApplicationController
  before_action :set_blog_post, except: %i[index new create] # only: %i[show edit update destroy]
  before_action :check_if_user_signed_in, except: %i[index show]

  def index
    @blog_posts = user_signed_in? ? BlogPost.all : BlogPost.published

    @pagy, @blog_posts = pagy(@blog_posts)
  end

  def show; end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new
    end
  end

  def edit; end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.all.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def check_if_user_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<div class="p-4 flex-col gap-2">
  <%= form_with model: blog_post do |form| %>
    <% if form.object.errors.any? %>
      <div>
        <% form.object.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>
    <div class="p-3 flex gap-3">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="p-3 flex gap-3 items-center">
      <%= form.label :content %>
      <div class="flex-col"><%= form.rich_text_area :content %></div>
    </div>
    <div class="p-3 flex gap-3">
      <%= form.label :published_at %>
      <%= form.datetime_select :published_at %>
    </div>
    <%= form.button class: "rounded bg-blue-300 p-4 font-bold" %>
  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<div>
  <p>Edit Blog</p>
</div>

<%= render partial: "form" , locals: {blog_post: @blog_post} %>

<%= button_to "Delete" ,@blog_post ,method: :delete , data: {turbo_confirm: "Are you sure?"}%>

app/views/blog_posts/index.html.erb
<div class="flex flex-col p-4">
  <div>
    <h1>Blog</h1>
  </div>
  <div>
    <p class="underline text-blue-500"><%= link_to "New Blog Post", new_blog_post_path %></p>
  </div>
  <% @blog_posts.each do |post|%>
    <div class="border border-gray-300 p-3 m-3">
      <% if post.draft? %>
        <div>
          <p class="p-2 rounded bg-gray-100 text-gray-900">Draft</p>
        </div>
      <% elsif post.scheduled?%>
        <div>
          <p class="p-2 rounded bg-blue-100 text-blue-900">Scheduled</p>
        </div>
      <% end %>
      <div class="p-4">
        <h2 class="underline text-blue-500">
          <%= link_to post.title, blog_post_path(post) %>
        </h2>
        <p>
          <%= post.content %>
        </p>
      </div>
    </div>
  <% end %>
  <div class="p-4 mx-auto"><%== pagy_nav(@pagy) %></div>
  <div>
  </div>
</div>

app/views/blog_posts/new.html.erb
<div class="p-4 flex gap-2">
    <h1>New Blog Post</h1>
</div>

<%= render partial: "form" , locals: {blog_post: @blog_post}  %>

app/views/blog_posts/show.html.erb
<h1><%=@blog_post.title%></h1>
<h1><%=@blog_post.content%></h1>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="my-16" >
    <main class="container prose mx-auto">
      <p class="alert"><%= alert %></p>
      <div>
        <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
      <%= yield %>
      <p class="notice"><%= notice %></p>
    </main>
  </body>
</html>